version: '3.8'

services:
  db:
    restart: always
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - database_dockerizing:/var/lib/postgresql/data
      # - ./db:/docker-entrypoint-initdb.d/
    ports:
      - '1234:5432'

  app:
    build: .
    container_name: backend
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PORT=8000
      # JWT
      - SECRET_JWT=8X1RW3Bt3eRtTgk1O7JVKXj4DbbXua5CGOXWWulCibNWALC
    volumes:
      - ./src:/app/src
    ports:
      - '8000:8000'
    depends_on:
      - db

  pgadmin:
    restart: always
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db

volumes:
  database_dockerizing:
